import { createReadStream } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import type { Readable } from 'node:stream';

/**
 * Where evidence bytes live. Local disk for now; hosting is still an open
 * decision, and an in-Kingdom object store can replace this
 * class without touching the rest of the module.
 */
export abstract class EvidenceStorage {
  abstract put(key: string, data: Buffer): Promise<void>;
  abstract open(key: string): Readable;
}

export class LocalDiskStorage extends EvidenceStorage {
  private readonly root = resolve(process.env.EVIDENCE_DIR ?? 'storage/evidence');

  /** Keys are generated by the API ("<entityId>/<uuid>"), but the path is still checked to stay inside root. */
  private path(key: string) {
    const full = resolve(join(this.root, key));
    if (!full.startsWith(this.root + sep)) throw new Error('Evidence key escapes the storage root');
    return full;
  }

  async put(key: string, data: Buffer) {
    const full = this.path(key);
    await mkdir(dirname(full), { recursive: true, mode: 0o700 });
    // 'wx' never overwrites an existing file; 0600 keeps it private to the API user.
    await writeFile(full, data, { flag: 'wx', mode: 0o600 });
  }

  open(key: string) {
    return createReadStream(this.path(key));
  }
}
